add_requires("sfml")
target("chess")
    set_kind("binary")
    before_build(function (target)
        local dest_assets_dir = path.join(target:targetdir(), "assets")
        os.mkdir(dest_assets_dir)
        os.cp("assets/*", dest_assets_dir)
    end)
    set_languages("c++20")
    add_files("main.cpp")
    add_files("src/*.cpp")
    add_files("src/logic/*.cpp")
    add_files("src/pieces/*.cpp")
    add_files("src/ui/*.cpp")
    add_files("src/utils/*.cpp")
    add_includedirs("include")
    add_packages("sfml")